get_state()：可理解为设定状态，记录下数组被打乱的操作

set_state()：接收get_state()返回的值，并进行同样的操作

In [1]:
import numpy as np
 
state = np.random.get_state()
chance = np.random.randint(100)
np.random.set_state(state)
chance2 = np.random.randint(100)
 
print(chance,chance2)

49 49


In [5]:
import numpy as np
 
images_list=[1,2,3,4,5,6,7,8,9]
labels_list=[1,2,3,4,5,6,7,8,9]
 
state = np.random.get_state()
np.random.shuffle(images_list)
np.random.set_state(state)
np.random.shuffle(labels_list)
 
print(images_list)
print(labels_list)


[6, 5, 7, 8, 1, 3, 4, 2, 9]
[6, 5, 7, 8, 1, 3, 4, 2, 9]


In [6]:
np.array((3,4))

array([3, 4])

In [7]:
def sigmoid(x):
    """
    Compute the sigmoid function for the input here.
    Arguments:
    x -- A scalar or numpy array.
    Return:
    s -- sigmoid(x)
    """

    ### YOUR CODE HERE
    exp_x = np.exp(x)
    s = exp_x / (1 + exp_x)
    ### END YOUR CODE

    return s

In [8]:
s = sigmoid(0)

In [9]:
s

0.5

In [1]:
%run sgd.py

Running sanity checks...
iter 100: 0.004578
iter 200: 0.004353
iter 300: 0.004136
iter 400: 0.003929
iter 500: 0.003733
iter 600: 0.003546
iter 700: 0.003369
iter 800: 0.003200
iter 900: 0.003040
iter 1000: 0.002888
test 1 result: 8.414836786079764e-10
iter 100: 0.000000
iter 200: 0.000000
iter 300: 0.000000
iter 400: 0.000000
iter 500: 0.000000
iter 600: 0.000000
iter 700: 0.000000
iter 800: 0.000000
iter 900: 0.000000
iter 1000: 0.000000
test 2 result: 0.0
iter 100: 0.041205
iter 200: 0.039181
iter 300: 0.037222
iter 400: 0.035361
iter 500: 0.033593
iter 600: 0.031913
iter 700: 0.030318
iter 800: 0.028802
iter 900: 0.027362
iter 1000: 0.025994
test 3 result: -2.524451035823933e-09
----------------------------------------
ALL TESTS PASSED
----------------------------------------


In [6]:
%run word2vec.py

==== Gradient check for skip-gram with naiveSoftmaxLossAndGradient ====
Gradient check passed!
==== Gradient check for skip-gram with negSamplingLossAndGradient ====
Gradient check failed for negSamplingLossAndGradient Gradient.
First gradient error found at index (0, 0) in the vector of gradients
Your gradient: -3.450754 	 Numerical gradient: -4.043862

=== Results ===
Skip-Gram with naiveSoftmaxLossAndGradient
Your Result:
Loss: 11.16610900153398
Gradient wrt Center Vectors (dJ/dV):
 [[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [-1.26947339 -1.36873189  2.45158957]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
Gradient wrt Outside Vectors (dJ/dU):
 [[-0.41045956  0.18834851  1.43272264]
 [ 0.38202831 -0.17530219 -1.33348241]
 [ 0.07009355 -0.03216399 -0.24466386]
 [ 0.09472154 -0.04346509 -0.33062865]
 [-0.13638384  0.06258276  0.47605228]]

Expected Result: Value should approximate these:
Loss: 11.16610900153398
Grad

In [8]:
%sh get_dataset.sh

UsageError: Line magic function `%sh` not found (But cell magic `%%sh` exists, did you mean that instead?).


In [10]:
%run run.py

iter 10: 19.824024
iter 20: 20.136629
iter 30: 20.151500
iter 40: 20.211374
iter 50: 20.245379
iter 60: 20.300555
iter 70: 20.322475
iter 80: 20.495801
iter 90: 20.568950
iter 100: 20.531704
iter 110: 20.580190
iter 120: 20.618622
iter 130: 20.609395
iter 140: 20.585372
iter 150: 20.554925
iter 160: 20.564125
iter 170: 20.771104
iter 180: 20.853380
iter 190: 20.923905
iter 200: 20.929908
iter 210: 20.889862
iter 220: 20.905184
iter 230: 20.942613
iter 240: 21.031544
iter 250: 20.902544
iter 260: 20.856235
iter 270: 20.972358
iter 280: 21.174176
iter 290: 21.221036
iter 300: 21.318940
iter 310: 21.404315
iter 320: 21.538801
iter 330: 21.559796
iter 340: 21.541622
iter 350: 21.646356
iter 360: 21.684856
iter 370: 21.599441
iter 380: 21.617427
iter 390: 21.695500
iter 400: 21.731551
iter 410: 21.712416
iter 420: 21.686617
iter 430: 21.593475
iter 440: 21.535498
iter 450: 21.678677
iter 460: 21.692688
iter 470: 21.683116
iter 480: 21.750281
iter 490: 21.791192
iter 500: 21.730953
iter 510:

iter 3970: 21.895688
iter 3980: 22.015816
iter 3990: 21.929245
iter 4000: 21.964797
iter 4010: 21.971053
iter 4020: 21.953228
iter 4030: 22.121950
iter 4040: 22.067777
iter 4050: 22.007880
iter 4060: 21.931178
iter 4070: 21.743746
iter 4080: 21.593551
iter 4090: 21.465101
iter 4100: 21.317816
iter 4110: 21.394863
iter 4120: 21.344752
iter 4130: 21.466889
iter 4140: 21.382250
iter 4150: 21.377357
iter 4160: 21.315449
iter 4170: 21.226557
iter 4180: 21.206828
iter 4190: 21.149951
iter 4200: 21.230418
iter 4210: 21.195522
iter 4220: 21.172485
iter 4230: 21.250365
iter 4240: 21.309232
iter 4250: 21.245832
iter 4260: 21.192273
iter 4270: 21.234394
iter 4280: 21.358106
iter 4290: 21.465790
iter 4300: 21.450521
iter 4310: 21.505660
iter 4320: 21.451668
iter 4330: 21.348416
iter 4340: 21.310099
iter 4350: 21.258953
iter 4360: 21.237079
iter 4370: 21.350025
iter 4380: 21.628371
iter 4390: 21.510480
iter 4400: 21.493163
iter 4410: 21.595586
iter 4420: 21.812566
iter 4430: 21.838720
iter 4440: 21

iter 7880: 17.646669
iter 7890: 17.677111
iter 7900: 17.640079
iter 7910: 17.729822
iter 7920: 17.797979
iter 7930: 17.857408
iter 7940: 17.863540
iter 7950: 17.786985
iter 7960: 17.723191
iter 7970: 17.661304
iter 7980: 17.753969
iter 7990: 17.790630
iter 8000: 17.919918
iter 8010: 17.877235
iter 8020: 17.936214
iter 8030: 17.897006
iter 8040: 17.780224
iter 8050: 17.881410
iter 8060: 17.942202
iter 8070: 17.884637
iter 8080: 17.925579
iter 8090: 17.909884
iter 8100: 17.761963
iter 8110: 17.782431
iter 8120: 17.645100
iter 8130: 17.678450
iter 8140: 17.535168
iter 8150: 17.572671
iter 8160: 17.524454
iter 8170: 17.569737
iter 8180: 17.684895
iter 8190: 17.688939
iter 8200: 17.635878
iter 8210: 17.690688
iter 8220: 17.678746
iter 8230: 17.537430
iter 8240: 17.645011
iter 8250: 17.504925
iter 8260: 17.589965
iter 8270: 17.643703
iter 8280: 17.501125
iter 8290: 17.507573
iter 8300: 17.508729
iter 8310: 17.573579
iter 8320: 17.537889
iter 8330: 17.542920
iter 8340: 17.519810
iter 8350: 17

iter 11710: 14.354278
iter 11720: 14.281895
iter 11730: 14.316860
iter 11740: 14.400363
iter 11750: 14.435398
iter 11760: 14.533770
iter 11770: 14.332169
iter 11780: 14.311926
iter 11790: 14.413089
iter 11800: 14.361011
iter 11810: 14.348362
iter 11820: 14.274768
iter 11830: 14.237554
iter 11840: 14.247763
iter 11850: 14.256129
iter 11860: 14.332818
iter 11870: 14.158164
iter 11880: 14.158742
iter 11890: 14.094507
iter 11900: 14.156469
iter 11910: 14.087501
iter 11920: 14.118918
iter 11930: 14.131863
iter 11940: 14.165806
iter 11950: 14.179412
iter 11960: 14.168241
iter 11970: 14.074035
iter 11980: 14.025752
iter 11990: 14.119112
iter 12000: 14.177933
iter 12010: 14.174758
iter 12020: 14.130476
iter 12030: 14.040163
iter 12040: 14.007724
iter 12050: 13.855397
iter 12060: 13.827125
iter 12070: 13.804898
iter 12080: 13.873265
iter 12090: 13.755865
iter 12100: 13.721017
iter 12110: 13.770075
iter 12120: 13.884243
iter 12130: 13.876607
iter 12140: 13.860936
iter 12150: 13.809189
iter 12160

iter 15440: 12.271064
iter 15450: 12.167814
iter 15460: 12.100403
iter 15470: 12.069981
iter 15480: 12.167134
iter 15490: 12.148417
iter 15500: 12.233499
iter 15510: 12.243619
iter 15520: 12.292089
iter 15530: 12.305048
iter 15540: 12.312046
iter 15550: 12.270518
iter 15560: 12.110360
iter 15570: 12.231834
iter 15580: 12.263828
iter 15590: 12.244340
iter 15600: 12.165281
iter 15610: 12.171990
iter 15620: 12.167689
iter 15630: 12.250109
iter 15640: 12.206768
iter 15650: 12.221295
iter 15660: 12.186318
iter 15670: 12.142024
iter 15680: 12.140688
iter 15690: 12.163754
iter 15700: 12.156140
iter 15710: 12.137677
iter 15720: 12.198299
iter 15730: 12.157052
iter 15740: 12.176923
iter 15750: 12.116875
iter 15760: 12.086804
iter 15770: 12.118065
iter 15780: 12.129649
iter 15790: 12.121617
iter 15800: 12.048247
iter 15810: 12.018198
iter 15820: 12.034478
iter 15830: 12.077156
iter 15840: 12.179441
iter 15850: 12.167787
iter 15860: 12.184154
iter 15870: 12.175112
iter 15880: 12.097332
iter 15890

iter 19170: 11.100308
iter 19180: 11.018338
iter 19190: 11.082914
iter 19200: 11.067312
iter 19210: 11.049787
iter 19220: 11.046084
iter 19230: 11.076828
iter 19240: 11.108941
iter 19250: 11.040111
iter 19260: 11.046222
iter 19270: 11.028599
iter 19280: 11.015727
iter 19290: 10.968459
iter 19300: 10.970309
iter 19310: 10.991658
iter 19320: 10.904084
iter 19330: 10.948114
iter 19340: 11.008887
iter 19350: 11.096174
iter 19360: 11.008476
iter 19370: 11.102459
iter 19380: 11.093299
iter 19390: 11.055625
iter 19400: 11.035703
iter 19410: 11.128663
iter 19420: 11.208460
iter 19430: 11.227123
iter 19440: 11.226173
iter 19450: 11.171981
iter 19460: 11.145520
iter 19470: 11.076543
iter 19480: 11.108721
iter 19490: 11.103296
iter 19500: 11.103469
iter 19510: 11.080370
iter 19520: 11.128818
iter 19530: 11.205138
iter 19540: 11.198758
iter 19550: 11.201453
iter 19560: 11.211102
iter 19570: 11.177704
iter 19580: 11.222616
iter 19590: 11.172149
iter 19600: 11.192798
iter 19610: 11.257090
iter 19620

iter 22900: 10.712367
iter 22910: 10.719906
iter 22920: 10.637368
iter 22930: 10.644620
iter 22940: 10.626460
iter 22950: 10.580922
iter 22960: 10.583633
iter 22970: 10.617167
iter 22980: 10.580997
iter 22990: 10.634659
iter 23000: 10.652066
iter 23010: 10.693910
iter 23020: 10.696029
iter 23030: 10.749112
iter 23040: 10.786023
iter 23050: 10.786527
iter 23060: 10.747248
iter 23070: 10.775266
iter 23080: 10.697465
iter 23090: 10.728087
iter 23100: 10.777779
iter 23110: 10.773600
iter 23120: 10.833773
iter 23130: 10.742415
iter 23140: 10.755452
iter 23150: 10.718753
iter 23160: 10.764867
iter 23170: 10.718558
iter 23180: 10.757851
iter 23190: 10.814255
iter 23200: 10.753145
iter 23210: 10.765653
iter 23220: 10.731599
iter 23230: 10.707706
iter 23240: 10.699470
iter 23250: 10.711093
iter 23260: 10.732518
iter 23270: 10.731421
iter 23280: 10.688710
iter 23290: 10.692386
iter 23300: 10.683792
iter 23310: 10.658719
iter 23320: 10.653855
iter 23330: 10.635372
iter 23340: 10.660925
iter 23350

iter 26630: 10.214643
iter 26640: 10.116379
iter 26650: 10.107512
iter 26660: 10.100369
iter 26670: 10.086305
iter 26680: 10.161660
iter 26690: 10.234310
iter 26700: 10.297943
iter 26710: 10.392745
iter 26720: 10.432897
iter 26730: 10.385263
iter 26740: 10.384107
iter 26750: 10.326193
iter 26760: 10.321864
iter 26770: 10.371733
iter 26780: 10.374269
iter 26790: 10.339557
iter 26800: 10.285856
iter 26810: 10.369235
iter 26820: 10.403694
iter 26830: 10.484914
iter 26840: 10.473976
iter 26850: 10.451148
iter 26860: 10.434000
iter 26870: 10.406361
iter 26880: 10.423477
iter 26890: 10.369267
iter 26900: 10.434705
iter 26910: 10.452023
iter 26920: 10.475307
iter 26930: 10.447199
iter 26940: 10.463741
iter 26950: 10.444420
iter 26960: 10.454810
iter 26970: 10.452928
iter 26980: 10.515298
iter 26990: 10.564333
iter 27000: 10.564950
iter 27010: 10.556618
iter 27020: 10.523255
iter 27030: 10.510455
iter 27040: 10.509832
iter 27050: 10.478400
iter 27060: 10.442926
iter 27070: 10.415988
iter 27080

iter 30370: 10.308724
iter 30380: 10.332597
iter 30390: 10.376529
iter 30400: 10.285126
iter 30410: 10.350778
iter 30420: 10.313440
iter 30430: 10.349018
iter 30440: 10.291900
iter 30450: 10.305206
iter 30460: 10.275759
iter 30470: 10.310320
iter 30480: 10.285366
iter 30490: 10.296713
iter 30500: 10.299295
iter 30510: 10.254583
iter 30520: 10.196548
iter 30530: 10.174303
iter 30540: 10.125963
iter 30550: 10.131882
iter 30560: 10.125541
iter 30570: 10.096164
iter 30580: 10.089039
iter 30590: 10.068709
iter 30600: 10.078594
iter 30610: 10.061951
iter 30620: 10.106485
iter 30630: 10.086918
iter 30640: 10.088329
iter 30650: 10.041305
iter 30660: 10.048118
iter 30670: 10.071291
iter 30680: 10.051041
iter 30690: 10.120566
iter 30700: 10.157712
iter 30710: 10.175428
iter 30720: 10.105290
iter 30730: 10.109028
iter 30740: 10.116715
iter 30750: 10.122690
iter 30760: 10.241763
iter 30770: 10.276567
iter 30780: 10.197061
iter 30790: 10.217654
iter 30800: 10.200198
iter 30810: 10.209078
iter 30820

iter 34170: 9.886025
iter 34180: 9.952814
iter 34190: 9.991747
iter 34200: 10.042627
iter 34210: 10.056689
iter 34220: 10.056272
iter 34230: 10.055227
iter 34240: 10.107123
iter 34250: 10.166042
iter 34260: 10.107122
iter 34270: 10.042852
iter 34280: 10.030624
iter 34290: 10.007907
iter 34300: 10.016908
iter 34310: 9.982668
iter 34320: 9.931906
iter 34330: 9.913066
iter 34340: 9.973527
iter 34350: 9.995617
iter 34360: 9.950051
iter 34370: 9.997320
iter 34380: 9.953448
iter 34390: 9.977645
iter 34400: 9.950014
iter 34410: 9.976493
iter 34420: 9.924114
iter 34430: 9.906028
iter 34440: 9.854563
iter 34450: 9.885881
iter 34460: 9.879361
iter 34470: 9.922409
iter 34480: 9.930446
iter 34490: 9.855877
iter 34500: 9.859743
iter 34510: 9.818521
iter 34520: 9.942114
iter 34530: 9.961372
iter 34540: 9.981912
iter 34550: 9.872590
iter 34560: 9.830272
iter 34570: 9.829298
iter 34580: 9.858357
iter 34590: 9.847919
iter 34600: 9.901590
iter 34610: 9.858307
iter 34620: 9.858823
iter 34630: 9.917693
it

iter 38030: 9.888444
iter 38040: 9.880309
iter 38050: 9.943584
iter 38060: 9.969726
iter 38070: 9.932403
iter 38080: 9.876058
iter 38090: 9.877038
iter 38100: 9.823513
iter 38110: 9.811443
iter 38120: 9.814547
iter 38130: 9.936990
iter 38140: 9.953968
iter 38150: 9.994132
iter 38160: 10.011087
iter 38170: 9.967864
iter 38180: 9.908851
iter 38190: 9.880031
iter 38200: 9.828075
iter 38210: 9.825149
iter 38220: 9.842239
iter 38230: 9.825868
iter 38240: 9.864336
iter 38250: 9.859332
iter 38260: 9.838446
iter 38270: 9.876360
iter 38280: 9.802579
iter 38290: 9.825347
iter 38300: 9.830335
iter 38310: 9.841431
iter 38320: 9.874300
iter 38330: 9.827438
iter 38340: 9.831419
iter 38350: 9.822916
iter 38360: 9.803061
iter 38370: 9.889704
iter 38380: 9.899184
iter 38390: 9.893826
iter 38400: 9.995356
iter 38410: 9.970846
iter 38420: 9.960194
iter 38430: 9.992831
iter 38440: 9.909429
iter 38450: 9.927183
iter 38460: 9.959456
iter 38470: 9.911201
iter 38480: 9.915312
iter 38490: 9.900423
iter 38500: 